### ISSUE TITLE
Copy-pasta on Softlayer --> Feature request

### ISSUE THREAD

**Issue by jszroberto** [jutkko/copy-pasta#14]
Copy-pasta works on Softlayer too !!! 👍  

The problem I was getting is described here: http://stackoverflow.com/questions/42259295/container-storage-location-with-specified-provisioning-code-not-available

The solution was to change the S3LOCATION:

```export S3LOCATION=us-standard```
Example of URL for SL would be: 

```
export S3ENDPOINT=s3-api.wdc-us-geo.objectstorage.softlayer.net

```

Could you make the login to optionally ask for those variables or having defaults for SL? It's a little inconvenient at the moment.  

It would be also great to have the S3LOCATION and URL inside of the targets file, so we can use buckets from different providers.

**Comment by jutkko** [comment]
@jszroberto thanks a lot for trying it out! I mainly tried to make it work on amazon s3 to start with. But the options thing sounds like a good idea. 

Maybe something like `copy-pasta login --s3location S3LOCATION --s3endpoint S3ENDPOINT`?

**Comment by jutkko** [comment]
@jszroberto if you find yourself constantly logging in, try the script in usecases. It is written to make your login easier.

**Comment by jutkko** [comment]
The implementation is there. Still need to update the flag's help.

**Comment by jutkko** [comment]
Done.

**Comment by jszroberto** [comment]
@jutkko amazing, 👍  I will give a try later :smile
