### ISSUE TITLE
Alternative storage backends?

### ISSUE THREAD

**Issue by Xeoncross** [jutkko/copy-pasta#18]
Are there any other storage engines planed beyond S3?

1. Adding a simple password/AES encrypt would allow use to paste content securely onto public paste bin servers. 
2. Using additional credentials, you could use a single private https://gist.github.com repo or similar free (private) store.

**Comment by jutkko** [comment]
Hi @Xeoncross, thanks for commenting. I had initially planned to make `copy-pasta` multiple backend supporting. But I started dealing with other things...

1. I am not sure what do you mean by the first point.
2. The idea of using gits on github sounds interesting. I will take a look at some point.

**Comment by jutkko** [comment]
@Xeoncross github gist support is here. You can try it out.
