### ISSUE TITLE
The tool does not work in vim!

### ISSUE THREAD

**Issue by jutkko** [jutkko/copy-pasta#5]
`:.!copy-pasta` in vim breaks the pasting... Sad.

**Comment by jutkko** [comment]
I think vim mode makes the tool think that there is stdin and therefore tries to read. Maybe can have a fallback command like `copy-pasta --paste`

**Comment by jszroberto** [comment]
Top priority 😄

**Comment by jutkko** [comment]
It will be nice to have this feature, but what would you really use it for? @jszroberto

**Comment by jutkko** [comment]
Might have a way to do it, need to write some tests for that.

**Comment by jutkko** [comment]
Also, the next step would be to have a simple vim plugin :)

**Comment by jutkko** [comment]
Dusted. Use --paste to force paste. See new issue #15.
