### ISSUE TITLE
Empty target

### ISSUE THREAD

**Issue by js3611** [jutkko/copy-pasta#6]
When you type:  "copy-pasta target" without target name, you get the following error:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x26bc]

goroutine 1 [running]:
panic(0x3368c0, 0xc4200140b0)
	/usr/local/Cellar/go/1.7.5/libexec/src/runtime/panic.go:500 +0x1a1
main.minioClient(0x0, 0xd4, 0xc4200912c0, 0x0)
	${GOPATH}/src/GitHub.com/jutkko/copy-pasta/main.go:61 +0x5c
main.main()
	${GOPATH}/src/GitHub.com/jutkko/copy-pasta/main.go:27 +0x94

Please fix this ASAP.

**Comment by jutkko** [comment]
Fixed in the newest commit! Thanks for reporting! :)
